# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint

# Import API key
from api_keys import g_key
gmaps.configure(api_key = g_key)

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
output_data_file = "weather_df.csv"
# output_data_file

weather_df = pd.read_csv(output_data_file)

weather_df.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,qaanaaq,0,GL,1584020615,44,77.48,-69.36,-17.05,5.66
1,1,nalut,0,LY,1584020884,26,30.33,10.85,66.15,13.04
2,2,jamestown,90,US,1584020511,93,42.10,-79.24,41.00,3.36
3,3,likhoslavl,100,RU,1584020885,73,57.13,35.46,40.50,9.04
4,4,mataura,2,NZ,1584020610,89,-46.19,168.86,48.99,3.00

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
locations = weather_df[["Lat", "Lng"]]
# locations

humidity = weather_df["Humidity"].astype(float)

fig = gmaps.figure()

heatmap_layer = gmaps.heatmap_layer(locations, weights=humidity,
                                   dissipating=False, max_intensity=5,
                                   point_radius=1)

fig.add_layer(heatmap_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
#A max temperature lower than 80 degrees but higher than 70.
#Wind speed less than 10 mph.
#Zero cloudiness.
#Drop any rows that don't contain all three conditions. You want to be sure the weather is ideal.

new_weather_df = pd.DataFrame(weather_df, columns = ["City", "Max Temp", "Wind Speed", "Cloudiness"])

max_temp = (new_weather_df["Max Temp"] <= 80) & (new_weather_df["Max Temp"] > 70)
wind_speed = new_weather_df["Wind Speed"] < 10
cloudiness = new_weather_df["Cloudiness"] == 0

new_weather_df[max_temp & wind_speed & cloudiness].head()

            City  Max Temp  Wind Speed  Cloudiness
7           tura     75.22        4.07           0
21      hermanus     71.01        8.99           0
73  punta arenas     73.42        6.26           0
79      khagaria     78.84        4.36           0
87      santa fe     73.96        2.39           0

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
hotel_df = pd.DataFrame(weather_df, columns=["City", "Country", "Lat", "Lng"])

hotel_df["Hotel Name"] = ""
hotel_df.head()

         City Country    Lat     Lng Hotel Name
0     qaanaaq      GL  77.48  -69.36
1       nalut      LY  30.33   10.85
2   jamestown      US  42.10  -79.24
3  likhoslavl      RU  57.13   35.46
4     mataura      NZ -46.19  168.86

In [6]:
target_location = f"{hotel_df['Lat'][0]},{hotel_df['Lng'][0]}"
target_keyword = "hotel"
target_radius = 5000
target_type = "hotel"

# set up a parameters dictionary
params = {
    "location": target_location,
    "keyword": target_keyword,
    "radius": target_radius,
    "type": target_type,
    "key": g_key
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# run a request using our params dictionary
response = requests.get(base_url, params=params)

In [7]:
pprint(response.json())

{'html_attributions': [],
 'results': [{'geometry': {'location': {'lat': 77.4692867, 'lng': -69.2315911},
                           'viewport': {'northeast': {'lat': 77.47071577989271,
                                                      'lng': -69.23000472010729},
                                        'southwest': {'lat': 77.46801612010727,
                                                      'lng': -69.23270437989272}}},
              'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
              'id': '57948e4c8303f471d71d38f6ded198a566166cb0',
              'name': 'Qaanaaq Hotel',
              'photos': [{'height': 2304,
                          'html_attributions': ['<a '
                                                'href="https://maps.google.com/maps/contrib/105406142912184834854">Jens-Peter '
                                                'Kleist</a>'],
                          'photo_reference': 'CmRaAAAAP6VEwp_yrze6s0oywfam6M37pQutjzkgeFqXVSH5-XFizjWAt-JjqvZkVUEYjNv_xoUNK4ttAOu5h3woYtqQ5idzXyOp0iJUD4ahMokw6mn5FsyIsmhkApCLQZKyxGhbEhAE7GTkGre75VebAk_dBgMqGhR0zcrvELPDhoVa_0hcdrUI6WfK3g',
                          'width': 4096}],
              'place_id': 'ChIJ29xdXLvJNU4RF7Y_k7vClTY',
              'plus_code': {'compound_code': 'FQ99+P9 Qaanaaq, Greenland',
                            'global_code': 'C79GFQ99+P9'},
              'rating': 4.7,
              'reference': 'ChIJ29xdXLvJNU4RF7Y_k7vClTY',
              'scope': 'GOOGLE',
              'types': ['lodging', 'point_of_interest', 'establishment'],
              'user_ratings_total': 27,
              'vicinity': 'Qaanaaq'}],
 'status': 'OK'}

In [8]:
hotel_df.iloc[0][0]

'qaanaaq'

In [18]:
#creates a list to capture hotel_names to insert into dataframe
hotel_names = []

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "hotel",
    "keyword": "hotel",
    "key": g_key
}

# taken from Airpost_Ratings Example done in class
for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]

    params["location"] = f"{lat},{lng}"

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    address = requests.get(base_url, params=params)
    
    # convert to json
    address = address.json()
    try:
        hotel_names.append(address['results'][0]['name'])
    except IndexError:
        hotel_names.append(np.nan)

In [19]:
hotel_names

['Qaanaaq Hotel',
 nan,
 'Chautauqua Harbor Hotel',
 'Pirani Hotel',
 "Ellie's Villa",
 'Melia Coco Beach',
 'Doubletree By Hilton Hotel Chongqing Wanzhou',
 'Hotel Polo Orchid',
 'Longteng Hotel',
 nan,
 'Hotel Krishna Residency',
 nan,
 'Arakur Ushuaia Resort & Spa',
 'Sheraton Kauai Resort at Coconut Beach',
 'Keleti Beach Resort',
 nan,
 'Reeds Bay Resort Hotel',
 'Hotel Castagneto',
 'Friendship International Hotel',
 'Holiday Inn Express & Suites Norman',
 'Duques de Medinaceli',
 'The Marine Hermanus',
 nan,
 'The Explorer Hotel',
 'Best Western Danbury/Bethel',
 'Palm Spring Resort Hotel Myitkyina',
 'The Rarotongan Beach Resort & Lagoonarium',
 "Pension Maro'i",
 'Aulani, A Disney Resort & Spa',
 nan,
 nan,
 'Hotel Molino Viejo',
 'Abrishami Hotel',
 'Foveaux Hotel',
 'Hotel Prabhu Residency',
 nan,
 'Hotel Austral Viedma',
 'Gostinitsa "Zapolyar\'ye"',
 'Protea Hotel by Marriott Takoradi Select',
 'Sandaun Surf Hotel',
 'Sitka Hotel & Restaurant',
 'Bannisters by the Sea',
 'Båtsfjord Hotell As',
 'Les Embruns Du Baril',
 'Tara Hotel',
 'Pushe Hotel',
 nan,
 'Best Western Thompson Hotel & Suites',
 'Hotel Farah',
 nan,
 'REER XOOSHLE GROUP',
 nan,
 nan,
 'Hilton Garden Inn Lompoc',
 'Hotel Uitonniemi',
 'Hattusa Vacation Thermal Club Erzin',
 'Isles Sunset Lodge',
 'Hotel Pousada Paraíso',
 nan,
 'Holiday Inn Express & Suites Morristown',
 'Pousada do Beco Shangri-La',
 'Hotel Kap Farvel',
 'Hotel Punta León',
 nan,
 nan,
 nan,
 'Shelikof Lodge',
 nan,
 'Desert Gat',
 'Frobisher Inn',
 nan,
 'Clarion Cedar Court Huddersfield Hotel',
 nan,
 nan,
 'Hotel Zumrat',
 'Hotel Moroccan House Casablanca',
 nan,
 'Esplanade Hotel',
 'Mercure Bengkulu',
 'Hotel Aryavart',
 'Moli International Hotel',
 'Radisson Blu Hotel, Tromsø',
 'Mercure Launceston',
 'Taloa Heights',
 'Camp Ripan',
 nan,
 'Pechenga',
 nan,
 nan,
 'Esperance Chalet Village',
 'Dredge 7 Inn',
 'Ulvesund Fyr',
 'Vardø Hotel AS',
 'Top of the World Hotel',
 'Hôtel Hiva Oa Hanakee Lodge',
 'Hotel Angmagssalik',
 'BIG4 Sunset Beach Holiday Park',
 '別邸 海と森',
 'Hotel Weidenhof',
 'Pousada Maria Bonita',
 'Kuri Beach View Inn',
 'Chunlei Hotel',
 'Mauritius-Holiday',
 'Villa Mbanandi Lodge',
 'Hotel Falter Hof',
 'Hotel Delina',
 nan,
 'Transit Boutique Service Apartment',
 'Hôtel Teriya',
 'Saskylakh Aeroport',
 'The Crown Inn Stornoway',
 nan,
 'HOTEL VILLA MARIA',
 nan,
 'Hotel First Class',
 'Hotel Mar Azul y Surf · Hotel en Suances',
 'Hotel Grand Chancellor Hobart',
 'La Cabaña Guainiana',
 'Panamericana Hotel Ancud',
 'Preskil Island Resort',
 nan,
 'The Bungalow Hambantota',
 'MY FINE STAY',
 'Holiday Inn Express & Suites N Waco Area - West',
 'Eastern & Oriental Hotel, Penang',
 nan,
 nan,
 "Tigil'",
 'Tateyama Seaside Hotel',
 'Hotel Buchanan Liberia',
 'Hotel Fonseca',
 'Hospedaje Familiar El Ciprés',
 'Tourist House - Sablino',
 'Pousada Amigos do Vento',
 nan,
 'Al Nakhel Hotel',
 'Hotel Centras',
 'Hotel Baleares',
 nan,
 nan,
 'Hotel Mi Tampi',
 'Microtel Inn & Suites by Wyndham Estevan',
 'The Garden Hotel Korla',
 'Hotel La Muradana',
 'Hoedjiesbaai Hotel',
 'Complexo Hoteleira Machikitchiki',
 'Thula Lodge',
 'Chita Lodge Kafue',
 'بلاك بيرد للسياحه',
 nan,
 'La Quinta Inn & Suites by Wyndham Alice',
 'DASTAN',
 'Gostevoy Dom "Brusnika"',
 'Hotel Plaza Lebu',
 nan,
 '6 On Kloof Guesthouse',
 'Gostinitsa "Shchara"',
 'Charleston Harbor Resort and Marina',
 nan,
 'The Gascoyne Hotel',
 nan,
 'Hôtel Matagami',
 'Quality Hotel Oceans Tutukaka',
 nan,
 'Hampton Inn Dulles/Cascades',
 nan,
 'Pond Country Club',
 'Playa Paraíso Gastronomía & Lodge',
 'Black Rock Oceanfront Resort',
 'Hotel Intercity Suape Costa Dourada',
 'Airotel Achaia Beach',
 'Parkhotel Auberge Vincent',
 'Beringgorski',
 "Grands' Guesthouse",
 'La Quinta Inn & Suites by Wyndham Searcy',
 nan,
 nan,
 'Westmark Fairbanks Hotel & Conference Center',
 'Coral Cay Resort',
 'ホテルマイステイズ名寄',
 nan,
 'Casa dos Lagos - AL',
 nan,
 nan,
 'BERLIAN HOTEL',
 'Hotel Nemuro Kaiyoutei',
 nan,
 nan,
 'Hotel Edda Höfn',
 'Hotel Puerto Sherry',
 'AZIMUT Отель Мирный',
 nan,
 'Kak Doma',
 'Ahipara Bay Motel',
 nan,
 "Gina's Guesthouse - Upernavik",
 'Side Trax Inn',
 'The Harbourview',
 'Seasun Beach Resort & Hotel',
 'Tianyuan International Hotel',
 'Hostería De La Cascada',
 'Angora Hotel',
 'Shri Dauji Guest House',
 'Auyuittuq Lodge (Inns North)',
 nan,
 'Swiss-Belhotel Sorong',
 'Hotel Santa Cruz',
 'Hotel Sarang Intercontinental',
 nan,
 'Scandic Alta',
 'Al Camar Lodge',
 'Nino village',
 'TWO MOUNTAINS LODGE',
 'Just Natur Guesthouse',
 'Miguel Angel Hotel',
 nan,
 'Dorado Beach, a Ritz-Carlton Reserve',
 'W Barcelona',
 'Amiin Hotel',
 'Hotel Restaurant Ter Linde',
 'Dolphin Bay Resort & Peleliu Divers',
 'Salalah Gardens Hotel',
 'Hotel Buganville Express',
 'Holiday Inn Express and Suites Havelock',
 nan,
 'Empire Hotel',
 'Black Mountain Lodge',
 nan,
 'Golden Park Hotel',
 'Ponta Anchaca',
 'Hotel Alankar Golden',
 'InterContinental Bora Bora Resort Thalasso Spa',
 'Stony River Boutique Hotel',
 'Airotel Achaia Beach',
 'Hôtel Teriya',
 'Damusa Guest Inn',
 'Aspen Suites Hotel Haines',
 nan,
 nan,
 nan,
 nan,
 'Penterstar Kgabo Resort, Mochudi',
 'Cabañas El Potrero',
 'Austral Hotel',
 'Hotel Elcano Acapulco',
 nan,
 'Desert Gardens Hotel - Ayers Rock Resort',
 'Maui Beach Hotel',
 'Hôtel Teriya',
 'The Gateway Resort Damdama Lake Gurgaon',
 'Hôtel Le Couvent Royal Saint Maximin',
 'Sakaiminato Yunagi no Yu Onyado Nono',
 'Moevenpick Enshi',
 'HOtel Tasiast',
 'Gostinitsa Zverevo',
 nan,
 'Lancaster Inn',
 "Eko Otel' Bol'shaya Medveditsa",
 nan,
 'at Rest',
 nan,
 nan,
 nan,
 'Baltic Beach Hotel & SPA',
 nan,
 'GAAT HOTEL',
 'MAFLAB International Hotel',
 'Chukotka hotel',
 'Gostinitsa Po Domashnemu',
 nan,
 nan,
 'Hilmarsstova a Hobbit Hole',
 'Hotel Cavalieri',
 nan,
 nan,
 'GrandStay® Residential Suites Hotel – Faribault',
 nan,
 'Sheraton Zhenjiang Hotel',
 'Boambee Bay Resort',
 'Kavieng Niu Lodge',
 'La Pirogue Mauritius',
 nan,
 'Villa Fratta',
 'Red Lion Inn & Suites Susanville',
 'Lava Guesthouse',
 'Clarion Cedar Court Huddersfield Hotel',
 'Nan Taw Oo',
 "Hunter's B&B",
 nan,
 'Seeadler Bay Hotel',
 'Red Roof Inn Clyde',
 nan,
 'Radisson Blu Polar Hotel, Spitsbergen',
 'Hotel Amazonia Cayenne',
 "Munitsipal'naya Gostinitsa",
 'Enjoy Coquimbo Hotel de la Bahía',
 'Hotel Gutierrez',
 nan,
 'Jinjiang Inn Yantai Fushan District Fuhai Road',
 'Last Light Lodge',
 'Bear River Casino Resort',
 'Acácia Hotel',
 "Hampton by Hilton Ji'an",
 'Grand Hotel',
 'Gostinitsa "Sever"',
 nan,
 'Vila Baleira Resort',
 nan,
 'Bowlish House',
 'Hotel Bambou',
 nan,
 'Katsuura Hotel Mikazuki',
 'Pousada Sollares',
 'Hotel Restaurant Ter Linde',
 'Nile Palace Hotel',
 nan,
 'Hotel Ilha Graciosa',
 'Gaúcho Hotel',
 nan,
 'Gostinitsa',
 'Pullman Zamzam Makkah',
 'Chaleanor Hotel',
 'Nacala Plaza Business Design Hotel',
 "Le Château D'en Haut Jenlain",
 'Hotel Resort Musdalifah',
 'Quality Inn Sept-Iles',
 'Hampton Inn Sheridan',
 'フサキビーチリゾート ホテル＆ヴィラズ',
 'Hotel Maritim Skjervøy AS',
 'DoubleTree by Hilton Wellington',
 'Hotel Bodega Real',
 'Hotel Sulmar',
 nan,
 'Homer Inn & Spa',
 'Dolphin Hotel',
 'Mahavira Hotel',
 'Odar kanawal',
 'Crown Victoria Hotel',
 'Garni Le Maddalene',
 'Dongfang Hotel',
 'Swiss Belhotel Manokwari',
 nan,
 nan,
 'Holiday Inn Express - Leigh Sports Village',
 'Westmark Fairbanks Hotel & Conference Center',
 'ROOM Motels',
 'Grand Hotel',
 nan,
 'Dormy Inn Honhachinohe',
 'Yi Yuan Holiday Hotel',
 'Chateau on the Park - Christchurch, a DoubleTree by Hilton',
 'Hotel Aldo',
 nan,
 'Ecohar Yoga',
 'Fosshotel Húsavík',
 'The Manor House at Celtic Manor',
 'Best Western Plus Waterfront Hotel',
 'The Landing Hotel',
 nan,
 nan,
 'Gostinitsa "Angara"',
 'Al Castello',
 'Auki Lodge',
 'Hotel "Soy bo‘yi"',
 'HOTEL LOCUS',
 'Enjoying Hotel',
 'Song Hotel Sydney',
 'Hengifoss Guesthouse',
 nan,
 'Hotel Miramar',
 'Grand Dafam Bela Ternate',
 nan,
 'Tibati Hotel',
 'Hotel Palace Itupiranga',
 'Otel Fatih',
 nan,
 'ibis Styles Karratha',
 'Balian Surf Villas',
 'LÜDERITZ NEST HOTEL',
 'Hotel Metro Tasikmalaya',
 'Eftopia Martino Pansion',
 nan,
 nan,
 'Codrington Gardens Bed And Breakfast',
 'Futura Hotel',
 'Pechora Gostinitsa',
 'Hilton Garden Inn Norwalk',
 'Sheraton Taitung Hotel',
 'Busta House Hotel',
 'Solomon Kitano Mendana Hotel',
 'Hotel Kununurra',
 'ООО Дуэт',
 'Harbour View',
 nan,
 'Best Western Linhares Design Hotel',
 'PRO LINK HOTEL',
 'Hotel & Spa Peñíscola Plaza Suites',
 'Les Chalets',
 'Turtle Beach By Elegant Hotels',
 'Sur Hotel',
 'Hotel Maniitsoq',
 'Quality Hotel & Suites',
 'Romax Hotel',
 'Raoum Inn Hotel',
 'Leshukonskaya, Gostinitsa',
 'Holiday Inn Express & Suites N Waco Area - West',
 'Sur Plaza Hotel',
 'Sanatoriy Toktamys',
 nan,
 'Four Points by Sheraton Manado',
 'Villa Ganz Boutique Hotel',
 'Hotel Arctic',
 'Ratskeller Wiedenbrück',
 'Mehamn Arctic Hotel AS',
 nan,
 'Horison Hotel',
 nan,
 'Hotel Taboka',
 'Bonthe Holiday Village',
 nan,
 'Untertelshof',
 'Atlantis Hotel',
 'Protea Hotel by Marriott George King George',
 'Gostinitsa Kedr',
 nan,
 'Hotel Klaksvík',
 'Grand Hotel "Uvat"',
 'BULDANA URBAN RESIDENCY CLUB',
 'Maceió Mar Hotel',
 'Wingate By Wyndham Rome',
 'iu Hotel Saurimo Rotunda',
 'Hotel Gavina Sens & Conference Center',
 'Smarthotel Hammerfest',
 'in Western',
 'Jingxi Hotel',
 nan,
 'Hotel Golden Scorpion',
 'Pousada do Amparo',
 'Hotel Olako',
 'Red Roof Inn Akron',
 nan,
 'Atankalama',
 'Hotel Narsaq',
 'Pazo do Souto',
 'Hotel Idelveis',
 nan,
 'Cassowary Hotel',
 'Penginapan Cantika',
 nan,
 'Grand Vilia Hotel',
 'Park Inn Haugesund Airport',
 nan,
 'Gostinnitsa',
 'بورتو بردية',
 'Granada Hotel Mandera',
 'Bertelli Chuí Hotel',
 'Americas Best Value Inn & Suites-Texas City/La Marque',
 'Best Western Plus Executive Hotel & Suites',
 'Krasnodar Marriott Hotel',
 'Aspen Extended Stay Suites',
 'Hotel Amanecer - Sechura',
 'Casa Rodo 53',
 nan,
 "The Trainmaster's Inn",
 'Zarya',
 'Fairfield Inn & Suites by Marriott Detroit Lakes',
 'Royal International Hotel',
 'Dhukurrdji Lodge',
 nan,
 'Hótel Dalvík',
 'SUNNY HOTEL Straubing',
 'VITS Devbhumi, Dwarka',
 'Hotel Casa Do Capitao',
 nan,
 nan,
 'Sri laxmi lodge',
 nan,
 nan,
 nan,
 'Sjøberg Ferie',
 'Pacific Harbour Lodge',
 'Prima Indah Hotel',
 'Prestige Hudson Bay Lodge',
 'Torreblanca Hotel',
 'ウトコ オーベルジュ＆スパ',
 'Гостиница "Турист"',
 'Beira Terrace Hotel',
 'Universal Gab Hotel',
 'Grand Hôtel La Cloche Dijon - MGallery',
 nan,
 'Hotel Protikka',
 nan,
 nan,
 'Pamuri Andes Lodge',
 'Hilton Knoxville Airport',
 'The Walper Hotel',
 nan,
 nan,
 'Fayton Hotel',
 nan,
 'Vagosh Hotel',
 'Inuk Hostels',
 'Van der Valk Hotel Apeldoorn - De Cantharel',
 nan,
 'Best Western Plus Bayshore Inn',
 'Mövenpick Hotel Qassim',
 'Royal Tulip Castle, Yenagoa',
 'Sing and Swing Lodge',
 'Groote Eylandt Lodge',
 'GMI lodge Kerema',
 'Hotel G Beach Resort and Restobar',
 "Manapescale (Chambre d'hôtes)",
 'Hotel SESC Oeiras',
 'Saraichik Hotel',
 'Hôtel Teriya',
 'The Lansdowne Hotel',
 "Krasnosel'kupnefteprodukt",
 'Hotel Playa El Cable',
 'Confiance Hotel',
 'Hotel Puerto Sherry',
 'Pacha Qori Backpackers',
 'Hotel New Amami',
 'Sado Green Hotel Kiraku',
 'Hotel Elite',
 nan,
 '新宮ユーアイホテル',
 nan,
 'Druk Deothjung',
 'Holiday Inn Hinton',
 'Moinho do Poço Verde',
 'فندق علي',
 'Blue Planet São Jorge Azores AL',
 'Mountain Hotel',
 'One to Z Hotel',
 'Chongqing White Cloud Boutique Hotel',
 'Radisson Blu Hotel, Dakar Sea Plaza',
 'Baohan Hotel',
 'Modern Hotel',
 nan,
 "Asliddin's Hause",
 'Hotel y restaurante "El Diamante"',
 nan,
 'Villavela Hotel Boutique',
 'Shangri-La Hotel, Nanchang',
 'Hotel Centrum Malbork',
 'Daios Cove Luxury Resort & Villas',
 'Lilin Lovina Beach Hotel',
 'Hotel Laguna Blu',
 'The Towne Motel',
 'Missão Católica de Caconda',
 'Hotel Pinezhskaya Sloboda',
 'Overlander Motor Lodge pty ltd.',
 'Camping Restaurante La Estanca',
 nan,
 'Agriturismo Sa Costa',
 'Opuwo Country Lodge',
 'Hotel Salta',
 'Zhemchug',
 'Atlantique Panorama',
 nan,
 nan,
 'HOSTAL PATIVILCA',
 'Southern Beach Hotel & Resort Okinawa',
 'Mercure Padang',
 'ICHEHAN LODGE',
 'hotêl doufoulougou',
 'Xique Xique Palace Hotel',
 'Hotel Hilltone']

In [20]:
hotel_df['Hotel Name']= hotel_names
hotel_df.dropna()
hotel_df.head()

         City Country    Lat     Lng               Hotel Name
0     qaanaaq      GL  77.48  -69.36            Qaanaaq Hotel
1       nalut      LY  30.33   10.85                      NaN
2   jamestown      US  42.10  -79.24  Chautauqua Harbor Hotel
3  likhoslavl      RU  57.13   35.46             Pirani Hotel
4     mataura      NZ -46.19  168.86            Ellie's Villa

In [22]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [23]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
fig.add_layer(markers)
fig
# Display Map

Figure(layout=FigureLayout(height='420px'))