# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
from pprint import pprint
%matplotlib

# Import API key
from api_keys import g_key
gmaps.configure(api_key = g_key)

Using matplotlib backend: Qt5Agg

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
output_data_file = "weather_df.csv"
# output_data_file

weather_df = pd.read_csv(output_data_file)

weather_df.head()

,Unnamed: 0,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,qaanaaq,0,GL,1584020615,44,77.48,-69.36,-17.05,5.66
1,1,nalut,0,LY,1584020884,26,30.33,10.85,66.15,13.04
2,2,jamestown,90,US,1584020511,93,42.10,-79.24,41.00,3.36
3,3,likhoslavl,100,RU,1584020885,73,57.13,35.46,40.50,9.04
4,4,mataura,2,NZ,1584020610,89,-46.19,168.86,48.99,3.00

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [3]:
locations = weather_df[["Lat", "Lng"]]
# locations

humidity = weather_df["Humidity"].astype(float)

fig = gmaps.figure()

heatmap_layer = gmaps.heatmap_layer(locations, weights=humidity,
                                   dissipating=False, max_intensity=5,
                                   point_radius=1)

fig.add_layer(heatmap_layer)

fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [4]:
new_weather_df = pd.DataFrame(weather_df, columns = ["City", "Max Temp", "Wind Speed", "Cloudiness"])

max_temp = (new_weather_df["Max Temp"] <= 80) & (new_weather_df["Max Temp"] > 70)
wind_speed = new_weather_df["Wind Speed"] < 10
cloudiness = new_weather_df["Cloudiness"] == 0

new_weather_df[max_temp & wind_speed & cloudiness].head()

            City  Max Temp  Wind Speed  Cloudiness
7           tura     75.22        4.07           0
21      hermanus     71.01        8.99           0
73  punta arenas     73.42        6.26           0
79      khagaria     78.84        4.36           0
87      santa fe     73.96        2.39           0

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [5]:
hotel_df = pd.DataFrame(weather_df, columns=["City", "Country", "Lat", "Lng"])

hotel_df["Hotel Name"] = ""
hotel_df.head()

         City Country    Lat     Lng Hotel Name
0     qaanaaq      GL  77.48  -69.36
1       nalut      LY  30.33   10.85
2   jamestown      US  42.10  -79.24
3  likhoslavl      RU  57.13   35.46
4     mataura      NZ -46.19  168.86

In [6]:
target_location = f"{hotel_df['Lat'][0]},{hotel_df['Lng'][0]}"
target_keyword = "hotel"
target_radius = 5000
target_type = "hotel"

# set up a parameters dictionary
params = {
    "location": target_location,
    "keyword": target_keyword,
    "radius": target_radius,
    "type": target_type,
    "key": g_key
}

# base url
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

# run a request using our params dictionary
response = requests.get(base_url, params=params)

In [7]:
pprint(response.json())

{'html_attributions': [],
 'results': [{'geometry': {'location': {'lat': 77.4692867, 'lng': -69.2315911},
                           'viewport': {'northeast': {'lat': 77.47071577989271,
                                                      'lng': -69.23000472010729},
                                        'southwest': {'lat': 77.46801612010727,
                                                      'lng': -69.23270437989272}}},
              'icon': 'https://maps.gstatic.com/mapfiles/place_api/icons/lodging-71.png',
              'id': '57948e4c8303f471d71d38f6ded198a566166cb0',
              'name': 'Qaanaaq Hotel',
              'photos': [{'height': 2304,
                          'html_attributions': ['<a '
                                                'href="https://maps.google.com/maps/contrib/105406142912184834854">Jens-Peter '
                                                'Kleist</a>'],
                          'photo_reference': 'CmRaAAAAGNYKX46eJjGHTlwpoD6MpoppFgrz5PTjhWc8cF1nIStjsZnk-fMrge6QKyhiGFUOYL8dF74qBUEMDwMRUqsNR2Z8su2ezIgQG4pwHXWXhVnZIWwv2_sy1PqK94gih3kIEhCtp6nCGGFPrIRUaPWkq5b4GhRaLGmpZ2IgERl3O2tUa7gVWR87Jw',
                          'width': 4096}],
              'place_id': 'ChIJ29xdXLvJNU4RF7Y_k7vClTY',
              'plus_code': {'compound_code': 'FQ99+P9 Qaanaaq, Greenland',
                            'global_code': 'C79GFQ99+P9'},
              'rating': 4.7,
              'reference': 'ChIJ29xdXLvJNU4RF7Y_k7vClTY',
              'scope': 'GOOGLE',
              'types': ['lodging', 'point_of_interest', 'establishment'],
              'user_ratings_total': 27,
              'vicinity': 'Qaanaaq'}],
 'status': 'OK'}

In [8]:
hotel_df.iloc[0][0]

'qaanaaq'

In [9]:
#creates a list to capture hotel_names to insert into dataframe
hotel_names = []

# params dictionary to update each iteration
params = {
    "radius": 5000,
    "types": "hotel",
    "keyword": "hotel",
    "key": g_key
}

for index, row in hotel_df.iterrows():
    lat = row["Lat"]
    lng = row["Lng"]

    params["location"] = f"{lat},{lng}"

    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

    address = requests.get(base_url, params=params)
    
    # convert to json
    address = address.json()
    try:
        hotel_names.append(address['results'][0]['name'])
    except IndexError:
        hotel_names.append(np.nan)

In [10]:
hotel_names

['Qaanaaq Hotel',
 nan,
 'Chautauqua Harbor Hotel',
 'Pirani Hotel',
 "Ellie's Villa",
 'The St. Regis Bahia Beach Resort, Puerto Rico',
 'Doubletree By Hilton Hotel Chongqing Wanzhou',
 'Hotel Polo Orchid',
 'Longteng Hotel',
 'Hotel Restaurante América',
 'Saikrupa Lawns',
 nan,
 'Riviera Fueguina',
 'Kauai Shores Hotel',
 'Keleti Beach Resort',
 nan,
 'Grand Naniloa Hotel Hilo - a DoubleTree by Hilton',
 'Hotel Castagneto',
 'Friendship International Hotel',
 'Americas Best Value Inn Norman at Univ of Oklahoma',
 'Hotel Bodega Real',
 'The Marine Hermanus',
 nan,
 'The Explorer Hotel',
 'Best Western Danbury/Bethel',
 'Palm Spring Resort Hotel Myitkyina',
 'Sanctuary Rarotonga-On the Beach',
 "Pension Maro'i",
 "Marriott's Ko Olina Beach Club",
 nan,
 nan,
 'Hotel Molino Viejo',
 'Abrishami Hotel',
 'Foveaux Hotel',
 'Hotel Dhanashree',
 nan,
 'Hotel Austral Viedma',
 nan,
 'Protea Hotel by Marriott Takoradi Select',
 'Sandaun Surf Hotel',
 'Talon Lodge & Spa',
 'Bannisters by the Sea',
 'Polar Hotel',
 'Les Embruns Du Baril',
 'Tara Hotel',
 "Pu'er Meizihu New Century Hot Spring Hotel",
 nan,
 'Burntwood Hotel',
 'Hotel Farah',
 nan,
 'REER XOOSHLE GROUP',
 nan,
 nan,
 'Hilton Garden Inn Lompoc',
 'Hotel Uitonniemi',
 'Hattusa Vacation Thermal Club Erzin',
 nan,
 'Pousada Rio Bonito',
 nan,
 'Holiday Inn Express & Suites Morristown',
 'Pousada Encanto Abrolhos',
 'Hotel Kap Farvel',
 'Complejo Bahia Ballenas',
 nan,
 nan,
 nan,
 'Best Western Kodiak Inn and Convention Center',
 nan,
 'Desert Gat',
 'Frobisher Inn',
 nan,
 'Clarion Cedar Court Huddersfield Hotel',
 nan,
 nan,
 'Kosmos',
 'Hotel Moroccan House Casablanca',
 nan,
 'Esplanade Hotel',
 'Hotel Santika Bengkulu',
 'HOTEL BHAVANA(LUXURY YET AFFORDABLE)',
 'Moli International Hotel',
 'Radisson Blu Hotel, Tromsø',
 'Mercure Launceston',
 'Taloa Heights',
 'Camp Ripan',
 nan,
 'Pechenga',
 'Monte Leah Beach Resort',
 nan,
 'Esperance Island View Apartments',
 'Dredge 7 Inn',
 'Ulvesund FYR',
 'Vardø Hotel AS',
 'Top of the World Hotel',
 'Simplicité Marquises',
 'The Red House',
 'Ocean Centre Hotel',
 'Inubosaki Kanko Hotel',
 'Hotel Weidenhof',
 'Pousada Maria Bonita',
 'Noovilu Suites - The luxury guest house in Maldives',
 'Chunlei Hotel',
 'Shanti Maurice Resort & Spa',
 'Villa Mbanandi Lodge',
 'Hotel Falter Hof',
 'Hotel Delina',
 nan,
 'Transit Boutique Service Apartment',
 'Hôtel Teriya',
 nan,
 'Cabarfeidh Hotel',
 'Monte Leah Beach Resort',
 'HOTEL VILLA MARIA',
 nan,
 'Hotel First Class',
 'Hotel Costa Esmeralda Suites',
 'The Alabama Hotel',
 'La Cabaña Guainiana',
 'Panamericana Hotel Ancud',
 'Paradise Beach by Horizon Holidays',
 nan,
 'The Bungalow Hambantota',
 'Pebbles Inn',
 'Holiday Inn Express & Suites N Waco Area - West',
 'The Prestige Hotel Penang',
 nan,
 nan,
 nan,
 'Tateyama Seaside Hotel',
 'Hotel Buchanan Liberia',
 'Hotel Fonseca',
 'Hospedaje Familiar El Ciprés',
 'Tourist House - Sablino',
 'Bugaendrus Paradise',
 nan,
 'Al Nakhel Hotel',
 'Hotel Centras',
 'ibis Santiago Estacion Central',
 nan,
 nan,
 'Hotel Mi Tampi',
 'Hotel Estevan',
 'Silver Star Hotel',
 'Hotel La Muradana',
 'Baviana Beach Lodge',
 'Complexo Hoteleira Machikitchiki',
 nan,
 'Chita Lodge Kafue',
 'Taqwa Club',
 nan,
 'La Quinta Inn & Suites by Wyndham Alice',
 'DASTAN',
 'Gostevoy Dom "Brusnika"',
 'Hotel Plaza Lebu',
 nan,
 '6 On Kloof Guesthouse',
 'Gostinitsa "Shchara"',
 'Holiday Inn Charleston-Riverview',
 nan,
 'The Gascoyne Hotel',
 nan,
 'Hôtel Matagami',
 'Quality Hotel Oceans Tutukaka',
 nan,
 'Hampton Inn Dulles/Cascades',
 nan,
 'Novomar Pousada e Turismo Ltda',
 'Playa Paraíso Gastronomía & Lodge',
 'Black Rock Oceanfront Resort',
 'Hotel Intercity Suape Costa Dourada',
 'Airotel Achaia Beach',
 'The Bamboo & Chicken Inn',
 nan,
 "Grands' Guesthouse",
 'Holiday Inn Express & Suites Searcy',
 nan,
 nan,
 'Westmark Fairbanks Hotel & Conference Center',
 'Ocean International Hotel',
 'ホテルマイステイズ名寄',
 nan,
 'Casa dos Lagos - AL',
 nan,
 nan,
 'Global View Hotel',
 'Hotel Nemuro Kaiyoutei',
 nan,
 nan,
 'Hótel Höfn',
 'Hotel Puerto Sherry',
 'AZIMUT Отель Мирный',
 nan,
 'Kak Doma',
 'Ahipara Bay Motel',
 nan,
 "Gina's Guesthouse - Upernavik",
 'Side Trax Inn',
 'The Harbourview',
 'Seasun Beach Resort & Hotel',
 'Tianyuan International Hotel',
 'Mulen Hotel Tandil',
 'Angora Hotel',
 'Shri Dauji Guest House',
 'Auyuittuq Lodge (Inns North)',
 nan,
 'Vega Hotel Sorong',
 'Hotel Santa Cruz',
 'Hotel Gurudev Palace',
 nan,
 'Scandic Alta',
 'Les huiles essentielles aux comores',
 'Nino village',
 'TWO MOUNTAINS LODGE',
 'Just Natur Guesthouse',
 'Hotel San Miguel',
 nan,
 'Embassy Suites by Hilton Dorado del Mar Beach Resort',
 'Hotel SB Glow',
 'Amiin Hotel',
 'Hotel Restaurant Ter Linde',
 'Dolphin Bay Resort & Peleliu Divers',
 'Salalah Gardens Hotel',
 'Pousada Rota Dos Tropeiros',
 'Hampton Inn Havelock',
 nan,
 'Empire Hotel',
 'Foyles of Glasbury',
 nan,
 'Diamante Hotel',
 'Ponta Anchaca',
 'Hotel Alankar Golden',
 'InterContinental Bora Bora Resort Thalasso Spa',
 'Stony River Boutique Hotel',
 'Airotel Achaia Beach',
 'Hôtel Teriya',
 'Marabas Ultimate Hotels',
 'Aspen Suites Hotel Haines',
 nan,
 nan,
 nan,
 nan,
 'Penterstar Kgabo Resort, Mochudi',
 'Cabañas El Potrero',
 'Austral Hotel',
 'Hotel Las Brisas Acapulco',
 nan,
 'Sails in the Desert',
 'Maui Beach Hotel',
 'Hôtel Teriya',
 'The Gateway Resort Damdama Lake Gurgaon',
 'Hôtel Le Couvent Royal Saint Maximin',
 'Sakaiminato Yunagi no Yu Onyado Nono',
 'Moevenpick Enshi',
 'HOtel Tasiast',
 'Gostinitsa Zverevo',
 nan,
 'The Harbour Quarters Inn',
 "Eko Otel' Bol'shaya Medveditsa",
 nan,
 'at Rest',
 nan,
 nan,
 nan,
 'Baltic Beach Hotel & SPA',
 nan,
 'GAAT HOTEL',
 'MAFLAB International Hotel',
 'Chukotka hotel',
 'Hotel "Nord House"',
 nan,
 nan,
 'Hotel Tvoroyri',
 'Hotel Cavalieri',
 nan,
 nan,
 "The Inn at Shattuck-St. Mary's",
 nan,
 'Hyatt Regency Zhenjiang',
 'Bonville Lodge Pet Friendly B & B - Coffs Harbour',
 'Nusa Island Retreat',
 'La Pirogue Mauritius',
 nan,
 'Hotel Villa Cipriani',
 'Red Lion Inn & Suites Susanville',
 'Aska Hostel',
 'Clarion Cedar Court Huddersfield Hotel',
 'Nan Taw Oo',
 "Hunter's B&B",
 nan,
 'Seeadler Bay Hotel',
 'Red Roof Inn Clyde',
 nan,
 'Radisson Blu Polar Hotel, Spitsbergen',
 'Grand Hotel Montabo',
 "Munitsipal'naya Gostinitsa",
 'Enjoy Coquimbo Hotel de la Bahía',
 'Hotel Gutierrez',
 nan,
 '7 Days Inn',
 'Waiau Hotel',
 'Bear River Casino Resort',
 'Acácia Hotel',
 "Ji'an Hotel",
 'Grand Hotel',
 'Gostinitsa "Sever"',
 nan,
 'Vila Baleira Resort',
 nan,
 'The Thatched Cottage Inn',
 'Jimmy Hotel',
 nan,
 'Katsuura Hotel Mikazuki',
 'Pousada Sollares',
 'Hotel Restaurant Ter Linde',
 'Nile Palace Hotel',
 nan,
 'Graciosa Resort - Biosphere Island Hotel',
 'Hotel Fontana',
 nan,
 'Arktika',
 'Pullman Zamzam Makkah',
 'Chaleanor Hotel',
 'INDICO EXECUTIVO HOTEL',
 nan,
 'Hotel Resort Musdalifah',
 'Château Arnaud',
 'Alamo Motel',
 'はりはりはうす',
 'Skjervøy fiskecamp AS',
 'Wellesley Boutique Hotel',
 'Hotel Puerto Sherry',
 'Hotel Sulmar',
 nan,
 'Homer Inn & Spa',
 'Décalé Hotel',
 'Hotel Grand Papua Nabire',
 'Odar kanawal',
 'Crown Victoria Hotel',
 'Miraval Hotel',
 'Oriental Ventura',
 'Swiss Belhotel Manokwari',
 nan,
 nan,
 'Holiday Inn Express - Leigh Sports Village',
 'Westmark Fairbanks Hotel & Conference Center',
 'ROOM Motels',
 'Grand Hotel',
 nan,
 'Dormy Inn Honhachinohe',
 'Yi Yuan Holiday Hotel',
 'BreakFree on Cashel Christchurch',
 nan,
 nan,
 'Hotel Praia Dourada',
 'Fosshotel Húsavík',
 'ibis budget Newport',
 'Best Western Plus Waterfront Hotel',
 'My Place Hotel - Ketchikan, AK',
 nan,
 nan,
 'Gostinitsa "Angara"',
 'Al Castello',
 'Auki Lodge',
 'Hotel "Soy bo‘yi"',
 'HOTEL LOCUS',
 'Ramada Yichang Hotel',
 'Song Hotel Sydney',
 'Hengifoss Guesthouse',
 nan,
 'Hotel Miramar',
 'Tiara Inn',
 nan,
 'Tibati Hotel',
 'Hotel Palace Itupiranga',
 'Otel Fatih',
 nan,
 'ibis Styles Karratha',
 'Pondok Pitaya: Hotel, Surfing and Yoga',
 'Obelix Guesthouse',
 'Hotel Metro Tasikmalaya',
 nan,
 nan,
 nan,
 'Codrington Gardens Bed And Breakfast',
 'Minoa Palace Resort',
 'Pechora Gostinitsa',
 'Hilton Garden Inn Norwalk',
 'Sheraton Taitung Hotel',
 'Moorfield Hotel',
 'Coral Sea Resort & Casino',
 'Hotel Kununurra',
 'Gostinitsa Gobi',
 'Mar Guesthouse',
 nan,
 'Pousada Ritec',
 'PRO LINK HOTEL',
 'Hotel & Spa Peñíscola Plaza Suites',
 'Les Chalets',
 'Turtle Beach By Elegant Hotels',
 'Hotel Real',
 'Hotel Maniitsoq',
 'Quality Hotel & Suites',
 'Romax Hotel',
 'Raoum Inn Hotel',
 'Gostinitsa Mup Zhkkh',
 'Holiday Inn Express & Suites N Waco Area - West',
 'Sur Plaza Hotel',
 'Sanatoriy Toktamys',
 nan,
 'Four Points by Sheraton Manado',
 'Hotel Fénix',
 'Hotel Arctic',
 'Königs Hotel am Schlosspark',
 'Mehamn Arctic Hotel AS',
 nan,
 'Hotel Athaya',
 nan,
 'Hotel Taboka',
 'Bonthe Holiday Village',
 nan,
 'Untertelshof',
 'Brees Beach House',
 'Protea Hotel by Marriott George King George',
 'Gostinitsa Kedr',
 nan,
 'Eysturland Lodge',
 'Grand Hotel "Uvat"',
 'BULDANA URBAN RESIDENCY CLUB',
 'Maceió Mar Hotel',
 'Wingate By Wyndham Rome',
 'iu Hotel Saurimo Rotunda',
 'Hilton Garden Inn Iquique, Chile',
 'Smarthotel Hammerfest',
 'in Western',
 'Jingxi Hotel',
 nan,
 'Hotel Golden Scorpion',
 'Pousada do Amparo',
 'Hôtel Georges Faustin Aurat',
 'Red Roof Inn Akron',
 nan,
 'Hotel Noi Borde Loa',
 'Hotel Narsaq',
 'Pazo do Souto',
 'Bay House',
 nan,
 'Cassowary Hotel',
 'Hotel Kerinci',
 'Herrington Inn & Spa',
 'Grand Vilia Hotel',
 'Park Inn Haugesund Airport',
 nan,
 'Gostinitsa',
 'بورتو بردية',
 'Granada Hotel Mandera',
 'Turis Firper Hotel',
 'Candlewood Suites Texas City',
 'Holiday Inn Lake Charles W - Sulphur',
 'Krasnodar Marriott Hotel',
 'Aspen Extended Stay Suites',
 'Hotel Amanecer - Sechura',
 'Casa Rodo 53',
 nan,
 "The Trainmaster's Inn",
 'Dom Otdykha "Pastoral\'"',
 'Fairfield Inn & Suites by Marriott Detroit Lakes',
 'GreenTree Alliance Gansu Wuwei Commercial Pedestrian Street Hotel',
 'Dhukurrdji Lodge',
 nan,
 'Hótel Dalvík',
 'SUNNY HOTEL Straubing',
 'Ginger Dwarka',
 'Hotel Casa Do Capitao',
 nan,
 nan,
 'Sri laxmi lodge',
 nan,
 nan,
 nan,
 'Fjordbris Hotell AS',
 'Pacific Harbour Lodge',
 'Prima Indah Hotel',
 'Prestige Hudson Bay Lodge',
 'Sumak Wasi Hotel',
 'ウトコ オーベルジュ＆スパ',
 'Гостиница "Турист"',
 'Beira Terrace Hotel',
 'Universal Gab Hotel',
 'Grand Hôtel La Cloche Dijon - MGallery',
 nan,
 'Hotel Protikka',
 nan,
 nan,
 'Pamuri Andes Lodge',
 'Hilton Knoxville Airport',
 'The Walper Hotel',
 nan,
 nan,
 'Fayton Hotel',
 nan,
 'Vagosh Hotel',
 'Inuk Hostels',
 'Bilderberg Hotel De Keizerskroon',
 nan,
 'Best Western Plus Bayshore Inn',
 'Rollins Hotel',
 'Royal Tulip Castle, Yenagoa',
 'Sing and Swing Lodge',
 'Groote Eylandt Lodge',
 'GMI lodge Kerema',
 'Hotel G Beach Resort and Restobar',
 '"Plantation Bed and Breakfast',
 'Hotel SESC Oeiras',
 'Saraichik Hotel',
 'Hôtel Teriya',
 'The Old Rectory',
 nan,
 'Nuevo Hotel Constitucion',
 'Confiance Hotel',
 'Hotel Puerto Sherry',
 'Wyndham Costa del Sol Cajamarca',
 'Hotel New Amami',
 'Sadokamoko Onsen Kohanno Yado Yoshidaya',
 'Hotel Elite',
 nan,
 'Gran Hotel',
 nan,
 'Lingkhar Lodge',
 'Holiday Inn Express & Suites Hinton',
 nan,
 'فندق المواجيد',
 'Blue Planet São Jorge Azores AL',
 'Mountain Hotel',
 'One to Z Hotel',
 'Chongqing White Cloud Boutique Hotel',
 'Radisson Blu Hotel, Dakar Sea Plaza',
 'Linxia Hotel',
 'Modern Hotel',
 nan,
 'Sayakat',
 'Hotel y restaurante "El Diamante"',
 nan,
 'Villavela Hotel Boutique',
 'Shangri-La Hotel, Nanchang',
 'Premium Bed & Breakfast',
 'Karma Minoan',
 'Lilin Lovina Beach Hotel',
 'Hotel Laguna Blu',
 'The Towne Motel',
 'Missão Católica de Caconda',
 'Hotel Pinezhskaya Sloboda',
 'Maynestay Motel',
 'Parador de Alcañiz',
 nan,
 'Hotel Residence Hibiscus',
 'Opuwo Country Lodge',
 'Portezuelo Nuevo Hotel',
 'Zhemchug',
 'Hôtel Riad Asfi',
 nan,
 nan,
 'HOSTAL PATIVILCA',
 'Southern Beach Hotel & Resort Okinawa',
 'Mercure Padang',
 'Residencia du Basco',
 'hotêl doufoulougou',
 'Xique Xique Palace Hotel',
 'Sterling Mount Abu Resorts and Hotels']

In [11]:
hotel_df['Hotel Name']= hotel_names
hotel_df.dropna()
hotel_df.head()

         City Country    Lat     Lng               Hotel Name
0     qaanaaq      GL  77.48  -69.36            Qaanaaq Hotel
1       nalut      LY  30.33   10.85                      NaN
2   jamestown      US  42.10  -79.24  Chautauqua Harbor Hotel
3  likhoslavl      RU  57.13   35.46             Pirani Hotel
4     mataura      NZ -46.19  168.86            Ellie's Villa

In [12]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [13]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations)
fig.add_layer(markers)
fig
# Display Map

Figure(layout=FigureLayout(height='420px'))